CREATE SEQUENCE ACCOUNT_PAY_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

CREATE SEQUENCE INVEST_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

CREATE SEQUENCE COMMENTS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

CREATE SEQUENCE CARD_PAY_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

CREATE SEQUENCE CREDIT_INFO_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;
  
CREATE SEQUENCE HASHTAG_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


CREATE SEQUENCE PRESENT_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE PROJECT_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE;